name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  ubuntu-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Installing boost
        shell: bash
        run: sudo apt-get install -y libboost-program-options-dev

      - name: Cache Z3
        id: cache-z3
        uses: actions/cache@v2
        with:
          path: z3
          key: ${{ runner.OS }}-z3-static

      - name: Building Z3
        if: steps.cache-z3.outputs.cache-hit != 'true'
        shell: bash
        run: |
          git clone --depth 1 https://github.com/Z3Prover/z3.git
          cmake -S z3 -B z3/build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DZ3_BUILD_LIBZ3_SHARED=FALSE
          cmake --build z3/build --config $BUILD_TYPE --parallel 8

      - name: Installing Z3
        shell: bash
        working-directory: ${{github.workspace}}/z3/build
        run: sudo make install

      - name: Configure CMake
        shell: bash
        run: cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_QMAP_TESTS=ON

      - name: Build
        shell: bash
        run: |
          cmake --build "${{github.workspace}}/build" --config $BUILD_TYPE --parallel 8 --target qmap_heuristic
          cmake --build "${{github.workspace}}/build" --config $BUILD_TYPE --parallel 8 --target qmap_exact
          cmake --build "${{github.workspace}}/build" --config $BUILD_TYPE --parallel 8 --target qmap_heuristic_test
          cmake --build "${{github.workspace}}/build" --config $BUILD_TYPE --parallel 8 --target qmap_exact_test

      - name: Test
        working-directory: ${{github.workspace}}/build/test
        shell: bash
        run: |
          ./qmap_exact_test
          ./qmap_heuristic_test

      - name: Coverage
        shell: bash
        run: |
          cmake -S "${{github.workspace}}" -B "${{github.workspace}}/buildCov" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_QMAP_TESTS=ON -DCOVERAGE=1
          cmake --build "${{github.workspace}}/buildCov" --config Debug --target qmap_exact_test
          cmake --build "${{github.workspace}}/buildCov" --config Debug --target qmap_heuristic_test
          cd buildCov/test
          ./qmap_exact_test
          ./qmap_heuristic_test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true

  macOS-ci:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Installing boost
        shell: bash
        run: brew install boost;

      - name: Cache Z3
        id: cache-z3
        uses: actions/cache@v2
        with:
          path: z3
          key: ${{ runner.OS }}-z3-static

      - name: Building Z3
        if: steps.cache-z3.outputs.cache-hit != 'true'
        shell: bash
        run: |
          git clone --depth 1 https://github.com/Z3Prover/z3.git
          cmake -S z3 -B z3/build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DZ3_BUILD_LIBZ3_SHARED=FALSE
          cmake --build z3/build --config $BUILD_TYPE --parallel 8

      - name: Installing Z3
        shell: bash
        working-directory: ${{github.workspace}}/z3/build
        run: sudo make install

      - name: Configure CMake
        shell: bash
        run: cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_QMAP_TESTS=ON

      - name: Build
        shell: bash
        run: |
          cmake --build "${{github.workspace}}/build" --config $BUILD_TYPE --parallel 8 --target qmap_heuristic
          cmake --build "${{github.workspace}}/build" --config $BUILD_TYPE --parallel 8 --target qmap_exact
          cmake --build "${{github.workspace}}/build" --config $BUILD_TYPE --parallel 8 --target qmap_heuristic_test
          cmake --build "${{github.workspace}}/build" --config $BUILD_TYPE --parallel 8 --target qmap_exact_test

      - name: Test
        working-directory: ${{github.workspace}}/build/test
        shell: bash
        run: |
          ./qmap_exact_test
          ./qmap_heuristic_test

  windows-ci:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Boost
        id:   cache-boost
        uses: actions/cache@v2
        with:
          path: ${{github.workspace}}/boost_1_70_0
          key:  ${{ runner.OS }}-boost

      - name: Download boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        run: |
             C:\msys64\usr\bin\wget.exe https://dl.bintray.com/boostorg/release/1.70.0/source/boost_1_70_0.7z --no-check-certificate

      - name:  Building boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        shell: bash
        run: |
             "/c/Program Files/7-Zip/7z.exe" x boost_1_70_0.7z "-o${{github.workspace}}"
             cd boost_1_70_0
             echo "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\Llvm\x64\bin\" >> $GITHUB_PATH
             ./bootstrap.bat --with-toolset=clang-win
             ./b2.exe -j8 toolset=clang-win address-model=64 link=static threading=multi runtime-link=shared variant=release --build-type=minimal --with-program_options

      - name: Installing Boost
        shell: bash
        run: |
             export Boost_DIR="${{github.workspace}}\boost_1_70_0"
             setx path "%path%;${{github.workspace}}\boost_1_70_0"
             setx lib "%lib%;${{github.workspace}}\boost_1_70_0\stage\lib"
             setx libpath "%libpath%;${{github.workspace}}\boost_1_70_0\stage\lib"

      - name: Cache Z3
        id:   cache-z3
        uses: actions/cache@v2
        with:
          path: z3
          key:  ${{ runner.OS }}-z3

      - name:  Building Z3
        if:    steps.cache-z3.outputs.cache-hit != 'true'
        shell: bash
        run:   |
               git clone --depth 1 https://github.com/Z3Prover/z3.git
               cmake -S z3 -B z3/build -DCMAKE_BUILD_TYPE=$BUILD_TYPE -T "ClangCl"
               cmake --build z3/build --config $BUILD_TYPE --parallel 8

      - name:              Installing Z3
        shell:             bash
        working-directory: ${{github.workspace}}/z3/build
        run:               sudo make install

      - name:  Configure CMake
        shell: bash
        run:   cmake -S "${{github.workspace}}" -B "${{github.workspace}}/build" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DBUILD_QMAP_TESTS=ON -T "ClangCl" -DBoost_USE_STATIC_LIBS=ON -DBoost_USE_MULTITHREADED=ON -DBoost_USE_STATIC_RUNTIME=OFF

      - name:  Build
        shell: bash
        run:   |
               cmake --build "${{github.workspace}}/build" --config $BUILD_TYPE --parallel 8 --target qmap_heuristic
               cmake --build "${{github.workspace}}/build" --config $BUILD_TYPE --parallel 8 --target qmap_exact
               cmake --build "${{github.workspace}}/build" --config $BUILD_TYPE --parallel 8 --target qmap_heuristic_test
               cmake --build "${{github.workspace}}/build" --config $BUILD_TYPE --parallel 8 --target qmap_exact_test

      - name:              Test
        working-directory: ${{github.workspace}}/build/test
        shell:             bash
        run:               |
                           cd $BUILD_TYPE
                           ./qmap_exact_test
                           ./qmap_heuristic_test
